palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

format = "$username $directory $git_branch\n $character"

[character]
success_symbol = "[>](bold foam)"
error_symbol = "[x](bold love)"

[directory]
format = "[ $path ]($style)"
style = "fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:foam"
symbol = ""


[username]
disabled = false
format = "[$user ]($style)"
show_always = true
style_root = "fg:iris"
style_user = "fg:iris"
